### PR TITLE
Adds Flag --dependencies for Getting Only Dependencies in package.json dependencies

### PR DESCRIPTION
**Pull request by dapperdandev**

### CODE REVIEW

**Review by arei — APPROVED** [review]
Thanks for the PR!

**Comment by arei** [comment]
Actually, one concern... the issue wants to get ONLY dependencies, but this will get the root and dependencies. Can you add code to only return the dependencies?

**Comment by dapperdandev** [comment]
@arei Sure thing. Just to be clear, can you confirm: 

Default behavior should include root: it's only when the flag is passed that it should not?

**Comment by arei** [comment]
That’s what I’m thinking, otherwise, there is no difference with —dependencies...unless I’m missing something.

**Comment by dapperdandev** [comment]
Hmmm... From testing it locally, I believe it works as expected (though I'm adding a commit to make the x and y variables more semantic (I blame C# LINQ).

`licext --mode merge --target somefile` will merge licenses for the root folder and it's node_modules folder

`licext --mode merge --target somefile --dependencies` will only merge licenses for packages specified in the the `package.json`'s dependencies

diff

With that said, do you think it should also exclude any children of the specified dependencies or leave it as is?

So instead of 

```
Added  minimist LICENSE (node_modules\minimist\LICENSE)
Added  mkdirp minimist LICENSE (node_modules\mkdirp\node_modules\minimist\LICENSE)
Added  mkdirp LICENSE (node_modules\mkdirp\LICENSE)
Added  mkdirp minimist LICENSE (node_modules\mkdirp\node_modules\minimist\LICENSE)
Added  rimraf LICENSE (node_modules\rimraf\LICENSE)
```

It would be

```
Added  minimist LICENSE (node_modules\minimist\LICENSE)
Added  mkdirp LICENSE (node_modules\mkdirp\LICENSE)
Added  rimraf LICENSE (node_modules\rimraf\LICENSE)
```

**Review by arei — APPROVED** [review]

**Comment by arei** [comment]
Okay, ignore what I said earlier about it not working... I was looking at wrong branch.

**Comment by arei** [comment]
I think what you are seeing breaks down a little more than what you describe, possibly like this:

Behavior 1: Show the root license.
Behavior 2: Show the dependencies licenses.
Behavior 3: Show all inherited licenses from the dependencies.
Behavior 4: Behavior 1 and Behavior 2.
Behavior 5: Behavior 2 and Behavior 3.
Behavior 6: Behavior 1 and Behavior 3.
Behavior 7: Behavior 1 and Behavior 2 and Behavior 3.

Maybe we should have a switch to toggle between them like: 
```
--show root
--show dependencies
--show inherited
--show root,dependencies
--show dependencies,inherited
--show root,inherited
--show root,inherited,dependencies
```

We could also provide
```
---show all
```
Which would be the default and also the same as behavior 7.

Thoughts?

**Comment by dapperdandev** [comment]
@arei I like that.

It may be a few days to a couple of weeks before I can jump in again, but I can visualize the solution. I think there's an opportunity for a performance improvement in my array comparison too.

**Comment by arei** [comment]
no worries on the time frame. Appreciate you willing to take it on!

**Pull request closed without merging**
